language: node_js
node_js:
  - "6"
  - "7"

cache:
  directories:
    - node_modules

install: npm install

script:
  - npm run lint
  - npm run build

after_success:
  - git config --global user.name  "bubkoo"
  - git config --global user.email "bubkoo.wy@gmail.com"
  - git clone https://${GH_TOKEN}@${GH_REF} ${REPO_NAME}
  - make deploy
  - cd ${REPO_NAME} && git push "https://${GH_TOKEN}@${GH_REF}" master:master

env:
  global:
    - REPO_NAME: mickeyjsx.github.com
    - TARGET_DIR: mickey-vstar
    - GH_REF: github.com/mickeyjsx/mickeyjsx.github.com.git
