language: node_js
node_js:
  - "6"
  - "7"

cache:
  directories:
    - node_modules

install: npm install

before_script:
  - git config --global user.name  "bubkoo"
  - git config --global user.email "bubkoo.wy@gmail.com"
  - git clone https://${GH_TOKEN}@${GH_REF} site

script:
  - npm run lint
  - npm run build
  - make update
  - git push https://${GH_TOKEN}@${GH_REF} origin master

env:
  global:
    - GH_REF: github.com/mickeyjsx/mickeyjsx.github.com.git
    - secure: "eGI9stNbSiBoh3VeIN5FBZsWD8Ig+o68TwTRg6IbUpBGOPoMrsoFmPIVFJNjzrzJO1Ut8QttKTfWcHdzMaBxvFdbuvCj8CJO79rAMMAckkcGwImsDvuPpqi99+JXydekgQ15k1Rg0PcHcu6u0zjdp1A+Z8svEHICLsgtS4BvQLQqH27r1pKoooDVfjAt1obgRYKK2rrIeDkeY+Vl43zST6LM7V2GZnPPlmAATmXqS6uKvfpDT/kWYQ/et7dvnMe8C2C5oJkdnbgxeMQq3vhQWqfYIai8Dq6jS6sUxCsGi4jtJBbJzn2V+ZFk6K9ER9z83Si0vi0HcWouZ+ATvh8ZPNbYvOdPAeJrOKwjw19zfdCFs+3E1mybpryJAP4I9G7/cB9MhdhFDALF6KHRkHanZoqlhYerufrWcSRzhxv4ba2euB8oJ0yAEB3RJa7dF2IgBifE953ZA9wQ7VINkPUgR2DNfkPMP6/cHbspSd0/uS13ayalGO7R6yPekshiYlNEMu6bAlrTvkcjQg5xDLLrJSSi6Ss43euznUKbUkV7qyXfTdeNCJbQwl04uhZbIaCA79tybv6g2RW/I1A19CsRmb+2a8doYvY27MiDaJ04MVa9LQ8o1M5NZBiFsntyKpXDpUNircP8OhIpbrDqXTssuxHKJUw1KQaZEi0T4QniMX4="
