language: node_js

node_js:
  - "6"
  - "7"

install: npm install

script:
  - npm test
  - npm run build

after_success:
  - git config --global user.name  "bubkoo"
  - git config --global user.email "bubkoo.wy@gmail.com"
  - git clone https://$GH_TOKEN@$GH_REF
  - make deploy

env:
  global:
    - GH_REF: github.com/mickeyjsx/mickeyjsx.github.com.git
